# version: '3.8'

# services:
#   systemservice:
#     build: 
#       context: ./SystemService
#       dockerfile: Dockerfile
#     container_name: systemservice
#     # environment:
#     #   PORT: 5000
#     ports:
#       - "8000:8000"
#     depends_on:
#       - database
#     networks:
#       - app-network

#   userservice:
#     build: 
#       context: ./UsersService
#       dockerfile: Dockerfile
#     container_name: userservice
#     # environment:
#     #   PORT: 5000
#     ports:
#       - "6050:6050"
#     depends_on:
#       - database
#     networks:
#       - app-network

#   backend:
#     build: 
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: backend
#     environment:
#       PORT: 5000
#       TOKEN_SECRET: secret
#       CALLBACK_URL: http://localhost:5000/api/auth/callback
#       # CALLBACK_URL: http://backend:5000/api/auth/callback
#       SHRAGA_URL: https://shraga.shraga.branch-yesodot.org
#       ACCESS_TOKEN_NAME: vision-access-token
#       SYSTEM_UNAVAILABLE_URL: /unavailable
#       BEFORE_DATE: 14
#       AFTER_DATE: 7
#     ports:
#       - "5000:5000"
#     depends_on:
#       - systemservice
#       - database
#     networks:
#       - app-network

#   # ui:
#   #   build:
#   #     context: ./ui
#   #     dockerfile: Dockerfile
#   #   container_name: ui
#   #   ports:
#   #     - "3000:3000"
#   #   depends_on:
#   #     - backend
#   #   networks:
#   #     - app-network

#   # nginx:
#   #   image: nginx:latest
#   #   container_name: my-nginx
#   #   volumes:
#   #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
#   #   ports:
#   #     - "80:80"
#   #   depends_on:
#   #     - ui
#   #     - backend
#   #   networks:
#   #     - app-network

#   database:
#     image: mongo:latest
#     container_name: mongodb
#     ports:
#       - "27017:27017"
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge












version: '3.8'

services:
  systemservice:
    build: 
      context: ./SystemService
      dockerfile: Dockerfile
    container_name: systemservice
    # environment:
    #   PORT: 5000
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - app-network

  userservice:
    build: 
      context: ./UsersService
      dockerfile: Dockerfile
    container_name: userservice
    # environment:
    #   PORT: 5000
    ports:
      - "6050:6050"
    depends_on:
      - database
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      PORT: 5000
      TOKEN_SECRET: secret
      CALLBACK_URL: http://localhost:5000/api/auth/callback
      # CALLBACK_URL: http://backend:5000/api/auth/callback
      SHRAGA_URL: https://shraga.shraga.branch-yesodot.org
      ACCESS_TOKEN_NAME: vision-access-token
      SYSTEM_UNAVAILABLE_URL: /unavailable
      BEFORE_DATE: 14
      AFTER_DATE: 7
    ports:
      - "5000:5000"
    depends_on:
      - systemservice
      - database
    networks:
      - app-network

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: ui
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network



  database:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge










































