version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - app-network

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - ui
      - backend
    networks:
      - app-network

  database:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


# version: '3.8'

# services:
#   backend:
#     build: 
#       context: ./backend
#       dockerfile: Dockerfile
#     # env_file: ./backend/.env
#     environment:
#       PORT: 5000
#       TOKEN_SECRET: secret
#       CALLBACK_URL: http://localhost:5000/api/auth/callback
#       SHRAGA_URL: https://shraga.shraga.branch-yesodot.org
#       ACCESS_TOKEN_NAME: vision-access-token
#       SYSTEM_UNAVAILABLE_URL: /unavailable
#       BEFORE_DATE: 14
#       AFTER_DATE: 7
#     ports:
#       - "5000:5000"
#     depends_on:
#       - database
#     networks:
#       - host # נשתמש ברשת של המחשב המקומי, כך שלא נצטרך רשת מותאמת

#   ui:
#     build:
#       context: ./ui
#       dockerfile: Dockerfile
#     ports:
#       - "5173:5173"
#     depends_on:
#       - backend
#     networks:
#       - host

#   nginx:
#     image: nginx:latest
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#     ports:
#       - "80:80"
#     depends_on:
#       - ui
#       - backend
#     networks:
#       - host

#   database:
#     image: mongo:latest
#     container_name: mongodb
#     ports:
#       - "27017:27017"
#     networks:
#       - host

# # לא נצטרך להגדיר רשת מותאמת אישית, כי אנחנו משתמשים ב-`host`
# networks:
#   host:
#     external: true
